import 'dart:typed_data';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

class ShareReportData {
  final String title;
  final String date;
  final String machine;
  final int score;
  final String status;
  final String bp;
  final String sugar;
  final String temp;
  final String pulse;
  final String spo2;

  const ShareReportData({
    required this.title,
    required this.date,
    required this.machine,
    required this.score,
    required this.status,
    required this.bp,
    required this.sugar,
    required this.temp,
    required this.pulse,
    required this.spo2,
  });
}

class ShareHelper {
  ShareHelper._();

  // ── Public PDF bytes ────────────────────
  static Future<Uint8List> buildPdfBytes(ShareReportData data) =>
      _buildPdf(data);

  // ── Entry point ────────────────────────
  static Future<void> shareReport(
    BuildContext context,
    ShareReportData data,
  ) async {
    final shareText = _buildText(data);

    if (kIsWeb) {
      await Share.share(shareText, subject: 'My SmartHealth Report');
      return;
    }

    try {
      _showLoading(context, 'Preparing report...');

      final bytes = await _buildPdf(data);

      if (!context.mounted) return;
      Navigator.pop(context); // أقفل loading dialog

      final dir = await getTemporaryDirectory();
      final file = File('${dir.path}/SmartHealth_Report.pdf');
      await file.writeAsBytes(bytes);

      await Share.shareXFiles(
        [XFile(file.path, mimeType: 'application/pdf')],
        subject: 'My SmartHealth Report',
        text: shareText,
      );
    } catch (e) {
      if (context.mounted) {
        try {
          Navigator.pop(context);
        } catch (_) {}
        _showError(context, 'Failed to share report');
      }
    }
  }

  // ── Share text ───────────────────────────────────────────────
  static String _buildText(ShareReportData d) => 'SmartHealth Report\n'
      '${d.date}\n'
      '${d.machine}\n\n'
      'Health Score: ${d.score} / 100\n\n'
      'Blood Pressure : ${d.bp} mmHg\n'
      'Blood Sugar    : ${d.sugar} mg/dL\n'
      'Temperature    : ${d.temp} °C\n'
      'Pulse Rate     : ${d.pulse} bpm\n'
      'SpO2           : ${d.spo2} %\n\n'
      'Generated by SmartHealth App';

  // ── PDF Builder ──────────────────────────────────────────────
  static Future<Uint8List> _buildPdf(ShareReportData r) async {
    final doc = pw.Document();

    const blue = PdfColor.fromInt(0xFF2196F3);
    const blueDark = PdfColor.fromInt(0xFF1565C0);
    const textDark = PdfColor.fromInt(0xFF1A1A2E);
    const textGrey = PdfColor.fromInt(0xFF757575);
    const bgLight = PdfColor.fromInt(0xFFF5F7FA);
    const bd = PdfColor.fromInt(0xFFE0E0E0);
    const white = PdfColors.white;

    final sc = r.score >= 80
        ? PdfColor.fromInt(0xFF4CAF50)
        : r.score >= 60
            ? PdfColor.fromInt(0xFFFFA726)
            : PdfColor.fromInt(0xFFEF5350);

    pw.Widget vRow(String label, String val, String unit) => pw.Container(
          margin: const pw.EdgeInsets.only(bottom: 8),
          padding: const pw.EdgeInsets.symmetric(horizontal: 14, vertical: 10),
          decoration: pw.BoxDecoration(
            color: white,
            borderRadius: pw.BorderRadius.circular(10),
            border: pw.Border.all(color: bd),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(label,
                  style: pw.TextStyle(
                      fontSize: 12,
                      fontWeight: pw.FontWeight.bold,
                      color: textDark)),
              pw.Text('$val $unit',
                  style: pw.TextStyle(
                      fontSize: 12,
                      fontWeight: pw.FontWeight.bold,
                      color: textDark)),
            ],
          ),
        );

    doc.addPage(pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(32),
      build: (_) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          // ── Header ──────────────────────────────────────────
          pw.Container(
            padding: const pw.EdgeInsets.all(20),
            decoration: pw.BoxDecoration(
              gradient: pw.LinearGradient(
                colors: [blueDark, blue],
                begin: pw.Alignment.topLeft,
                end: pw.Alignment.bottomRight,
              ),
              borderRadius: pw.BorderRadius.circular(12),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('SmartHealth Report',
                        style: pw.TextStyle(
                            fontSize: 20,
                            fontWeight: pw.FontWeight.bold,
                            color: white)),
                    pw.SizedBox(height: 4),
                    pw.Text(r.title,
                        style: pw.TextStyle(fontSize: 13, color: white)),
                    pw.Text(r.date,
                        style: pw.TextStyle(fontSize: 11, color: white)),
                    pw.Text(r.machine,
                        style: pw.TextStyle(fontSize: 11, color: white)),
                  ],
                ),
                pw.Container(
                  width: 60,
                  height: 60,
                  decoration:
                      pw.BoxDecoration(color: white, shape: pw.BoxShape.circle),
                  child: pw.Center(
                    child: pw.Column(
                      mainAxisAlignment: pw.MainAxisAlignment.center,
                      children: [
                        pw.Text('${r.score}',
                            style: pw.TextStyle(
                                fontSize: 20,
                                fontWeight: pw.FontWeight.bold,
                                color: sc)),
                        pw.Text('/100',
                            style: pw.TextStyle(fontSize: 9, color: textGrey)),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 20),

          // ── Health Status ────────────────────────────────────
          pw.Container(
            padding:
                const pw.EdgeInsets.symmetric(horizontal: 14, vertical: 10),
            decoration: pw.BoxDecoration(
              color: bgLight,
              borderRadius: pw.BorderRadius.circular(10),
              border: pw.Border.all(color: bd),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Health Status',
                    style: pw.TextStyle(
                        fontSize: 13,
                        fontWeight: pw.FontWeight.bold,
                        color: textDark)),
                pw.Container(
                  padding: const pw.EdgeInsets.symmetric(
                      horizontal: 12, vertical: 4),
                  decoration: pw.BoxDecoration(
                    color: PdfColor(sc.red, sc.green, sc.blue, 0.15),
                    borderRadius: pw.BorderRadius.circular(20),
                  ),
                  child: pw.Text(r.status,
                      style: pw.TextStyle(
                          fontSize: 12,
                          fontWeight: pw.FontWeight.bold,
                          color: sc)),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 20),

          // ── Vitals ───────────────────────────────────────────
          pw.Text('Vitals Summary',
              style: pw.TextStyle(
                  fontSize: 14,
                  fontWeight: pw.FontWeight.bold,
                  color: textDark)),
          pw.SizedBox(height: 10),
          vRow('Blood Pressure', r.bp, 'mmHg'),
          vRow('Blood Sugar', r.sugar, 'mg/dL'),
          vRow('Temperature', r.temp, 'C'),
          vRow('Pulse Rate', r.pulse, 'bpm'),
          vRow('SpO2', r.spo2, '%'),

          pw.SizedBox(height: 24),
          pw.Divider(color: bd),
          pw.SizedBox(height: 8),
          pw.Text(
            'Generated by SmartHealth App - '
            '${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}',
            style: pw.TextStyle(fontSize: 10, color: textGrey),
            textAlign: pw.TextAlign.center,
          ),
        ],
      ),
    ));

    return Uint8List.fromList(await doc.save());
  }

  // ── Loading Dialog ───────────────────────────────────────────
  static void _showLoading(BuildContext context, String msg) {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (_) => AlertDialog(
        shape: const RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(16))),
        content: Row(children: [
          const CircularProgressIndicator(
              color: Color(0xFF2196F3), strokeWidth: 3),
          const SizedBox(width: 16),
          Text(msg, style: const TextStyle(fontSize: 14)),
        ]),
      ),
    );
  }

  // ── Error Dialog ─────────────────────────────────────────────
  static void _showError(BuildContext context, String msg) {
    showDialog(
      context: context,
      builder: (_) => AlertDialog(
        shape: const RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(16))),
        title:
            const Text('Error', style: TextStyle(fontWeight: FontWeight.bold)),
        content: Text(msg),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('OK'),
          ),
        ],
      ),
    );
  }
}
